#!/bin/sh

set -e

BASE_URL="https://digabi.fi/debian"
SRC_LIST="/etc/apt/sources.list.d/digabi.list"
APT_KEY="/etc/apt/trusted.gpg.d/digabi.gpg"
WGET="/usr/bin/wget"

get() {
    URL="$1"
    TARGET="$2"
    ${WGET} -O "${TARGET}" "${URL}"
}

if [ ! -f "${SRC_LIST}" ]
then
    get "${BASE_URL}/digabi.list" "${SRC_LIST}"
fi

if [ ! -f "${APT_KEY}" ]
then
    get "${BASE_URL}/digabi.gpg" "${APT_KEY}"
fi
